# Generated by Django 6.1.1 on 2026-10-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='editoras',
            new_name='publisher',
        ),
    ]
