# Generated by Django 6.1.1 on 2026-10-05 00:46

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_editoras_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(validators=[books.models.validar_data_publicacao]),
        ),
    ]
